,Artisan_Id,Name,Skill_Category,Years_Experience,Rating,Completed_Jobs,Complaint_Rate,Availability,Latitude,Longitude,City,Base_Price_Index
0,1,Douglas Kelley,Painter,9,3.96,743,0.100,Busy,11.971829,8.544256,Kano,0.80
1,2,Amanda Morris,Tailor,10,4.03,543,0.016,Offline,6.560566,3.386912,Lagos,1.17
2,3,Kaitlyn Diaz,AC Technician,24,4.98,235,0.038,Busy,9.115566,7.408295,Abuja,0.89
3,4,Justin Cook,Carpenter,5,3.53,731,0.018,Available,6.490916,7.541867,Enugu,1.02
4,5,Leonard Clark,Carpenter,23,3.60,927,0.063,Offline,12.027186,8.633304,Kano,1.06
...,...,...,...,...,...,...,...,...,...,...,...,...
494,495,Rachel Reyes,AC Technician,15,3.75,768,0.062,Busy,7.377913,3.929281,Ibadan,1.13
495,496,Nicholas Castillo,AC Technician,17,4.59,412,0.013,Available,6.500211,3.375599,Lagos,1.18
496,497,William Young,Tailor,18,4.40,703,0.066,Offline,7.340828,3.989775,Ibadan,0.88
497,498,Ian Turner,Tailor,14,3.18,205,0.093,Available,12.038970,8.612762,Kano,0.82
498,499,Mark Daniels,AC Technician,2,4.15,401,0.137,Offline,12.032996,8.618776,Kano,1.21

In [9]:
df_artisans

,Artisan_Id,Name,Skill_Category,Years_Experience,Rating,Completed_Jobs,Complaint_Rate,Availability,Latitude,Longitude,City,Base_Price_Index
0,1,Douglas Kelley,Painter,9,3.96,743,0.100,Busy,11.971829,8.544256,Kano,0.80
1,2,Amanda Morris,Tailor,10,4.03,543,0.016,Offline,6.560566,3.386912,Lagos,1.17
2,3,Kaitlyn Diaz,AC Technician,24,4.98,235,0.038,Busy,9.115566,7.408295,Abuja,0.89
3,4,Justin Cook,Carpenter,5,3.53,731,0.018,Available,6.490916,7.541867,Enugu,1.02
4,5,Leonard Clark,Carpenter,23,3.60,927,0.063,Offline,12.027186,8.633304,Kano,1.06
...,...,...,...,...,...,...,...,...,...,...,...,...
494,495,Rachel Reyes,AC Technician,15,3.75,768,0.062,Busy,7.377913,3.929281,Ibadan,1.13
495,496,Nicholas Castillo,AC Technician,17,4.59,412,0.013,Available,6.500211,3.375599,Lagos,1.18
496,497,William Young,Tailor,18,4.40,703,0.066,Offline,7.340828,3.989775,Ibadan,0.88
497,498,Ian Turner,Tailor,14,3.18,205,0.093,Available,12.038970,8.612762,Kano,0.82
498,499,Mark Daniels,AC Technician,2,4.15,401,0.137,Offline,12.032996,8.618776,Kano,1.21

In [10]:
df_artisans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artisan_Id        499 non-null    int64
 1   Name              499 non-null    object
 2   Skill_Category    499 non-null    object
 3   Years_Experience  499 non-null    int64
 4   Rating            499 non-null    float64
 5   Completed_Jobs    499 non-null    int64
 6   Complaint_Rate    499 non-null    float64
 7   Availability      499 non-null    object
 8   Latitude          499 non-null    float64
 9   Longitude         499 non-null    float64
 10  City              499 non-null    object
 11  Base_Price_Index  499 non-null    float64
dtypes: float64(5), int64(3), object(4)
memory usage: 46.9+ KB

In [11]:
df_artisans.describe()

,Artisan_Id,Years_Experience,Rating,Completed_Jobs,Complaint_Rate,Latitude,Longitude,Base_Price_Index
count,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000,499.000000
mean,250.000000,12.525050,3.997154,511.737475,0.070417,8.007476,6.429802,1.034569
std,144.193157,7.363543,0.581438,283.912781,0.043106,2.331241,1.872473,0.145124
min,1.000000,1.000000,3.000000,10.000000,0.000000,4.769536,3.330109,0.800000
25%,125.500000,6.000000,3.485000,252.500000,0.034500,6.476569,3.957136,0.910000
50%,250.000000,12.000000,3.980000,521.000000,0.066000,7.362847,7.379883,1.020000
75%,374.500000,19.000000,4.515000,762.000000,0.106500,10.472011,7.531331,1.150000
max,499.000000,25.000000,5.000000,1000.000000,0.150000,12.051012,8.641573,1.300000

In [13]:
df_artisans["Skill_Category"].value_counts()

Skill_Category
AC Technician    81
Jeweler          77
Electrician      76
Carpenter        75
Tailor           64
Plumber          64
Painter          62
Name: count, dtype: int64

In [14]:
df_artisans["City"].value_counts()

City
Lagos            79
Enugu            77
Port Harcourt    72
Kano             71
Abuja            71
Ibadan           69
Kaduna           60
Name: count, dtype: int64

In [18]:
df = df_artisans.copy()
# Normalize rating (assuming 3–5 range)
df["rating_score"] = (df["Rating"] - 3) / (5 - 3)
# Normalize experience (1–25 years assumed)
df["experience_score"] = df["Years_Experience"] / 25
# Convert complaint rate into positive score
df["complaint_score"] = 1 - df["Complaint_Rate"]
# Availability mapping
availability_map = {
   "Available": 1,
   "Busy": 0.5,
   "Offline": 0
}
df["availability_score"] = df["Availability"].map(availability_map)

In [20]:
df["rating_score"]

0      0.480
1      0.515
2      0.990
3      0.265
4      0.300
       ...
494    0.375
495    0.795
496    0.700
497    0.090
498    0.575
Name: rating_score, Length: 499, dtype: float64

In [21]:
df["experience_score"]

0      0.36
1      0.40
2      0.96
3      0.20
4      0.92
       ...
494    0.60
495    0.68
496    0.72
497    0.56
498    0.08
Name: experience_score, Length: 499, dtype: float64

In [22]:
df["complaint_score"]

0      0.900
1      0.984
2      0.962
3      0.982
4      0.937
       ...
494    0.938
495    0.987
496    0.934
497    0.907
498    0.863
Name: complaint_score, Length: 499, dtype: float64

In [23]:
df["availability_score"]

0      0.5
1      0.0
2      0.5
3      1.0
4      0.0
      ...
494    0.5
495    1.0
496    0.0
497    1.0
498    0.0
Name: availability_score, Length: 499, dtype: float64

In [25]:
!pip install geopy
from geopy.distance import geodesic
user_location = (6.5200, 3.3700)
def compute_distance(row):
   return geodesic(
       user_location,
       (row["Latitude"], row["Longitude"])
   ).km
df["distance_km"] = df.apply(compute_distance, axis=1)
# Normalize distance (closer = better)
max_distance = df["distance_km"].max()
df["distance_score"] = 1 - (df["distance_km"] / max_distance)

Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.1-py3-none-any.whl.metadata (1.6 kB)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
Downloading geographiclib-2.1-py3-none-any.whl (40 kB)
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.1 geopy-2.4.1

In [26]:
from geopy.distance import geodesic
user_location = (6.5200, 3.3700)
def compute_distance(row):
   return geodesic(
       user_location,
       (row["Latitude"], row["Longitude"])
   ).km
df["distance_km"] = df.apply(compute_distance, axis=1)
# Normalize distance (closer = better)
max_distance = df["distance_km"].max()
df["distance_score"] = 1 - (df["distance_km"] / max_distance)

In [27]:
df["distance_score"]

0      0.015745
1      0.994227
2      0.370628
3      0.451872
4      0.002518
         ...
494    0.865499
495    0.997298
496    0.864924
497    0.003244
498    0.003272
Name: distance_score, Length: 499, dtype: float64

In [29]:
requested_skill = "Electrician"
df_filtered = df[df["Skill_Category"] == requested_skill].copy()

In [30]:
df_filtered

,Artisan_Id,Name,Skill_Category,Years_Experience,Rating,Completed_Jobs,Complaint_Rate,Availability,Latitude,Longitude,City,Base_Price_Index,rating_score,experience_score,complaint_score,availability_score,distance_km,distance_score
10,11,Jonathan Dean,Electrician,11,3.17,925,0.015,Offline,4.773757,7.008579,Port Harcourt,1.07,0.085,0.44,0.985,0.0,446.946124,0.469100
11,12,Jessica Peterson,Electrician,9,4.89,45,0.055,Offline,9.043683,7.400408,Abuja,0.85,0.945,0.36,0.945,0.0,524.878500,0.376529
13,14,Holly Smith,Electrician,7,4.94,773,0.072,Busy,10.500531,7.447687,Kaduna,0.83,0.970,0.28,0.928,0.5,628.722341,0.253179
15,16,Amber Griffith,Electrician,10,3.31,890,0.121,Busy,4.832488,7.079666,Port Harcourt,1.12,0.155,0.40,0.879,0.5,451.319037,0.463906
17,18,Mary Baker,Electrician,18,4.44,845,0.068,Available,6.425278,7.587517,Enugu,0.83,0.720,0.72,0.932,1.0,466.635250,0.445713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,463,Joseph Hill,Electrician,6,3.70,461,0.123,Available,6.487778,3.424531,Lagos,1.14,0.350,0.24,0.877,1.0,7.005523,0.991679
470,471,Dennis Ibarra,Electrician,21,3.76,24,0.084,Busy,12.049846,8.637467,Kano,0.98,0.380,0.84,0.916,0.5,841.865121,0.000000
472,473,Kylie Henson,Electrician,6,4.77,557,0.143,Offline,6.416704,7.530590,Enugu,0.91,0.885,0.24,0.857,0.0,460.366376,0.453159
478,479,Kim Dickson,Electrician,8,4.56,435,0.079,Available,6.410883,7.539818,Enugu,1.27,0.780,0.32,0.921,1.0,461.405832,0.451924
486,487,Matthew Gordon,Electrician,15,3.05,792,0.089,Busy,7.343136,3.972180,Ibadan,0.83,0.025,0.60,0.911,0.5,112.761490,0.866058

In [31]:
df_filtered["final_score"] = (
   0.30 * df_filtered["rating_score"] +
   0.20 * df_filtered["distance_score"] +
   0.20 * df_filtered["experience_score"] +
   0.15 * df_filtered["availability_score"] +
   0.15 * df_filtered["complaint_score"]
)

In [32]:
df_filtered["final_score"]

10     0.355070
11     0.572556
13     0.611836
15     0.426131
17     0.738943
         ...
462    0.632886
470    0.494400
472    0.532682
478    0.676535
486    0.512362
Name: final_score, Length: 76, dtype: float64

In [35]:
top_artisans = df_filtered.sort_values(
   by="final_score",
   ascending=False
).head(5)
top_artisans[[
   "Artisan_Id",
   "Name",
   "Rating",
   "Years_Experience",
   "distance_km",
   "final_score"
]]

,Artisan_Id,Name,Rating,Years_Experience,distance_km,final_score
115,116,Teresa Bennett,4.54,19,4.419641,0.868000
196,197,Rebecca Rodriguez,4.56,24,5.006046,0.831661
78,79,Andrew Hernandez,4.91,24,629.365623,0.822533
179,180,Brittany Trujillo,4.97,20,464.427500,0.766717
45,46,Emily Bailey,4.78,24,528.198067,0.745617

In [38]:
import numpy as np
# Create booking probability using your ranking features
df_filtered["booking_probability"] = (
   0.4 * df_filtered["rating_score"] +
   0.3 * df_filtered["distance_score"] +
   0.3 * df_filtered["complaint_score"]
)
# Convert to 0/1 booking outcome
df_filtered["booked_successfully"] = np.random.binomial(
   1,
   df_filtered["booking_probability"]
)

In [41]:
df_filtered = df_filtered.reset_index(drop=True)

In [42]:
df_filtered["booked_successfully"]

0     1
1     1
2     1
3     0
4     1
     ..
71    0
72    1
73    1
74    1
75    1
Name: booked_successfully, Length: 76, dtype: int32

In [43]:
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

features = df_filtered[[

    "rating_score",

    "distance_score",

    "experience_score",

    "availability_score",

    "complaint_score"

]]

target = df_filtered["booked_successfully"]

X_train, X_test, y_train, y_test = train_test_split(

    features, target, test_size=0.2

)

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()